Added config and key generation for oauth signing key
nuts-foundation/nuts-auth pull request #103
Opened 2020-09-29 13:52 UTC by woutslakhorst

part of #101

2020-09-29 14:16 UTC, woutslakhorst commented
Moving PemToSigner to crypto module

2020-09-29 14:24 UTC, woutslakhorst commented
waiting for nuts-foundation/nuts-crypto#98

2020-10-01 08:10 UTC, reinkrul commented on README_options.rst
> +oAuthKeyGeneration         true            Auto generate OAuth JWT signing key if missing.
is this casing right? (oAuth/OAuth)

2020-10-01 08:13 UTC, reinkrul commented on engine/engine.go
> +	flags.String(oauth.ConfOAuthSigningKey, defs.OAuthSigningKey, "Path to PEM encoded private key.")
I had to read the code to realise the authorization server isn't enabled when this is empty, maybe add that to the config option explanation.

2020-10-01 08:14 UTC, reinkrul commented on pkg/services/oauth/oauth.go
> +	var (
shouldn't this be done by `nuts-crypto` so we can switch to other backends (like vault) more easily in the future?

2020-10-01 08:16 UTC, reinkrul commented on pkg/services/oauth/oauth.go
> +	pubBytes := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: der})
`EC PRIVATE KEY` vs `PUBLIC KEY`, shouldn't we mention `EC` here as well?

2020-10-01 08:18 UTC, reinkrul requested changes
see comments

2020-10-01 10:54 UTC, woutslakhorst commented
Going to change it to an always-on service with keys in crypto-storage. Will add some commands for extracting the pub key and key rotation

2020-10-02 09:59 UTC, woutslakhorst commented
continued in #111

2020-10-02 09:59 UTC, closed without merging