Oauth bearer sig
nuts-foundation/nuts-auth pull request #124
Opened 2020-10-19 14:31 UTC by woutslakhorst

2020-10-20 15:17 UTC, woutslakhorst commented
build failure due to some mac <> linux difference

2020-10-28 08:57 UTC, reinkrul requested changes

2020-10-28 08:57 UTC, reinkrul commented on pkg/services/oauth/oauth.go
> +		return nil, errors.New("JWT validity to long")
to -> too

2020-10-28 08:57 UTC, reinkrul commented on pkg/services/oauth/oauth.go
> +	actorPartyID, err := core.ParsePartyID(jwtBearerToken.Issuer)
do we have enough logging (e.g. of issuer PartyIDs which proved to be invalid) to analyse production issues? Or is the issuer mentioned in the returned error?

2020-10-28 08:57 UTC, reinkrul commented on pkg/services/oauth/oauth.go
> +			fmt.Errorf("no vendorID in SAN: %w", err)
return

2020-11-03 12:07 UTC, woutslakhorst commented
Covered by #131

2020-11-03 12:07 UTC, closed without merging