added a bearer token verify API
nuts-foundation/nuts-auth pull request #141
Opened 2020-11-09 15:33 UTC by woutslakhorst

This API can be used by a reverse proxy to do a delegated auth check.

For example, nginx: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-subrequest-authentication/

This will help in testing and endpoints that have no care context.

2020-11-10 09:32 UTC, reinkrul requested changes

2020-11-10 09:32 UTC, reinkrul commented on docs/_static/nuts-auth.yaml
> +        Verifies the access token given in the Authorization header (as bearer token). If it's a valid access token issued by this server, it'll return a 200 status code.
Ah, so this endpoint does not intent to implement RFC7662 (https://tools.ietf.org/html/rfc7662) but is sort of a helper API for proxies. I think that's a good solution vs. implementing the RFC in a disputed way.

2020-11-10 09:32 UTC, reinkrul commented on docs/_static/nuts-auth.yaml
> +            text/plain:
the implementation returns no content

2020-11-10 09:32 UTC, reinkrul commented on docs/_static/nuts-auth.yaml
> +          description: The given access token is invalid.
or it couldn't be verified

2020-11-10 09:32 UTC, reinkrul commented on api/api.go
> +		logrus.Warn("no authorization header given")
We usually start log messages with a capital (first character)

2020-11-10 15:19 UTC, woutslakhorst commented on docs/_static/nuts-auth.yaml
> +            text/plain:
removed from spec

2020-11-11 08:25 UTC, reinkrul approved these changes

2020-11-11 09:30 UTC, merged