added config option for enabling validators
nuts-foundation/nuts-auth pull request #145
Opened 2020-11-16 08:24 UTC by woutslakhorst

also updated deps

the idea is to add a dummy auth option in the future, but that depends on a validator refactor currently underway.

2020-11-16 15:15 UTC, reinkrul requested changes

2020-11-16 15:15 UTC, reinkrul commented on engine/engine.go
> +	flags.StringSlice(pkg.ConfContractValidators, defs.ContractValidators, "Set the different contract validators to use")
Sets

2020-11-16 15:15 UTC, reinkrul commented on pkg/types.go
> +	ContractValidators		  []string
indenting

2020-11-17 10:38 UTC, reinkrul approved these changes

2020-11-17 10:59 UTC, stevenvegt approved these changes

2020-11-17 11:29 UTC, merged